// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backbackend.Data;

#nullable disable

namespace rpg2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("backbackend.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("datenow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inputemail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inputname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("inputtel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requestnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vmodelday")
                        .HasColumnType("int");

                    b.Property<int?>("vmodelsumm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });
#pragma warning restore 612, 618
        }
    }
}
